### ISSUE TITLE
Lowest price doesn't seem to work anymore

### ISSUE THREAD

**Issue by jflambert** [CatxFish/psstore_metascore#1]
Don't know when it broke, but I'm using the latest chrome (83.0.4103.116) and extension (1.1.15) versions.

The metacritic does appear though

![image](https://user-images.githubusercontent.com/11539524/87172610-7fa17680-c2a2-11ea-8cee-a63ba604eb12.png)

**Comment by superflyxxi** [comment]
I noticed this while fixing this to support the new PlayStation Redesign #2. The URL was incorrect, so I fixed it.

**Comment by jflambert** [comment]
So can this be closed @CatxFish ?

**Comment by CatxFish** [comment]
This issue has been fixed.
